[tool.poetry]
name = "redshift-timer"
version = "0.1.0"
description = ""
authors = ["John Weachock <jweachock@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
astral = "^2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
